version: '3.1'

services:
  s_jenkins:
    container_name: c_jenkins
    image: jenkins/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data:
